version: "3.8"
services:
  mail:
    image: bytemark/smtp
    container_name: plausible_mail
    restart: unless-stopped

  plausible_db:
    image: postgres:14-alpine
    container_name: plausible_db
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - internal

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    container_name: plausible_events
    restart: always
    volumes:
      - ./event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    networks:
      - internal
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    container_name: plausible_prod
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    env_file: .env
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    networks:
      - internal
      - web
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.plausible.rule=Host(`plausible.yourdomain.com`)"
        - "traefik.http.routers.plausible.entrypoints=websecure"
        - "traefik.http.services.plausible.loadbalancer.server.port=8000"

volumes:
  db-data:
  event-data:
  clickhouse:

networks:
  web:
    external: true
  internal:
    external: false
